# -*- coding: utf-8 -*-
"""A8_Self.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFmWB0qobsiSynfgiYuhU1TgHQoeSUxJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = sns.load_dataset('titanic')
df.head()

df.info()

df.describe()

df.shape

sns.histplot(x='fare',data=df)
#sns.set(rc={'figure.figsize':(5,5)})

sns.displot(x='age',data=df,bins=70)

sns.catplot(x='survived', data=df, kind='count', hue='pclass')

plt.figure(figsize=(5,4))
vp=sns.violinplot(x='class',y='age',palette='rainbow',data=df)
plt.show()

plt.figure(figsize=(6,5))
ab=sns.stripplot(x='class',y='age',data=df)
plt.show()

plt.figure(figsize=(5,4))
wt=sns.swarmplot(x='class',y='age',data=df)
plt.show()

plt.figure(figsize=(5,4))
kl=sns.scatterplot(x='age',y='fare',data=df,hue='survived')
plt.show()

plt.figure(figsize=(6,4))
ad=sns.countplot(x='class',data=df)
for i in ad.containers:
  ad.bar_label(i)
plt.show()

