# -*- coding: utf-8 -*-
"""A9_Self.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xogadFSvMtQkSC9Ct9v1zOBi0gbwG_KF
"""

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('titanic')
df.head()

plt.figure(figsize=(8,4))
sns.boxplot(x='sex', y='age', data=df, hue='survived')
plt.title("Distribution of age with respect to each gender and Survival Status")
plt.xlabel("Sex")
plt.ylabel("Age")
plt.show()

"""Observations

We created a box plot of variables 'age & 'sex' & used survival as the hue

There we visualized three variables Age, Sex & Survival. Two out of these are categorical and one is numerical

Now in addition to the information about the age of each gender, you can also see the distribution of passengers who survived

For instance, you can see that among the male passengers, on average more younger people survived as compared to older ones
"""

ax=sns.barplot(x='sex',y='age',data=df, palette='Set2', hue='survived')

vp=sns.violinplot(x='sex',y='age',data=df, hue= 'survived')

ab=sns.stripplot(x='sex',y='age',data=df)

