# -*- coding: utf-8 -*-
"""Copy of A10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132qkUylEvdRn3YK1oC_suAoxJol8NJzf

10 Data Visualization III
Download the Iris flower dataset or any other dataset into a DataFrame. (e.g.,
https://archive.ics.uci.edu/ml/datasets/Iris ). Scan the dataset and give the inference as:
1. List down the features and their types (e.g., numeric, nominal) available in the dataset.
2. Create a histogram for each feature in the dataset to illustrate the feature distributions.
3. Create a boxplot for each feature in the dataset.
4. Compare distributions and identify outliers.
"""

import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('iris')

df

df.head()

df.info()

print(df.dtypes)

sns.histplot(x='sepal_length', data=df)

fig, axes = plt.subplots(2,2, figsize=(15, 10))
fig.suptitle('Histogram')
sns.histplot(x='sepal_length', data=df, ax=axes[0,0])
sns.histplot(x='sepal_width', data=df, ax=axes[0,1])
sns.histplot(x='petal_length', data=df, ax=axes[1,0])
sns.histplot(x='petal_width', data=df, ax=axes[1,1])

fig, axes = plt.subplots(2,2, figsize=(15, 10))
fig.suptitle('Boxplot')
sns.boxplot(y='sepal_length', x='species', data=df, ax=axes[0,0])
sns.boxplot(y='sepal_width', x='species', data=df, ax=axes[0,1])
sns.boxplot(y='petal_length', x='species', data=df, ax=axes[1,0])
sns.boxplot(y='petal_width', x='species', data=df, ax=axes[1,1])

"""https://dev.to/thalesbruno/subplotting-with-matplotlib-and-seaborn-5ei8

Conclusion

The Iris dataset consists of four numerical features (sepal length, sepal width, petal length, and petal width) and one categorical feature (species), which includes three classes: Setosa, Versicolor, and Virginica.

Histograms and boxplots revealed the distribution of each feature, with sepal width showing some outliers, identified using the IQR method.

Violin plots demonstrated the variation of different features across species, showing that Setosa is distinct from the other two species, while Versicolor and Virginica overlap in some features.

The pair plot indicated strong correlations, especially between petal length and petal width, confirming that these features contribute significantly to species classification.

The analysis helped visualize data distribution, identify outliers, and understand feature relationships, providing insights for further classification tasks.
"""

